module.exports=(sequelize,DataTypes)=>{
    const Lesson=sequelize.define('lesson',{
        id:{
            type:DataTypes.INTEGER,
            allowNull:false,
            autoIncrement:true,
            primaryKey:true
        },
        lessonName:{
            type:DataTypes.STRING,
            allowNull:false
        },
        Link:{
            type:DataTypes.STRING,
            allowNull:false
        },
        description:{
            type:DataTypes.STRING,
            allowNull:false
        },
        lessonImage:{
            type:DataTypes.STRING,
            allowNull:false
        },
        like:{
            type:DataTypes.INTEGER
        },
        courseId:{
            type:DataTypes.INTEGER,
            references:{
                model:'course',
                key:'id'
              },
              onUpdate:'CASCADE',
              onDelete:'SET NULL'
        },
        lessonId:{
            type:DataTypes.INTEGER
        },
        done:{
            type:DataTypes.BOOLEAN,
            defaultValue:false
        }
    })
    Lesson.associate=models=>{
        Lesson.belongsTo(models.course)
        Lesson.hasMany(models.question)
        Lesson.hasMany(models.comment)
        Lesson.belongsToMany(models.user,{through:models.like,as:'likeUser',foreignKey:'likeableId',constraints:false,scope:{likeableType:'User'}})
        
    }
    return Lesson;
}